pipeline {
    agent any

  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }
    stage('Package') {
        steps {
            script {
                sh 'echo "packaging stage"'
            }
        }
    }
    stage('Deploy') {
        steps {
            script {
                sh 'echo "Deploying"'
            }
        }
    }
    stage('Clean up') {
        steps {
            script {
                sh 'echo "Clening"'
            }
        }
    }
    }
}